name: CI

on: [push, pull_request]

jobs:
  all-1a:
    name: All 1a
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJson(github) }}
      USER_ID: ${{ github.event.sender.id }}
    steps:
      - run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV # Sets version env var.
      - run: echo "all-1a"
      - run: echo ${EVENT}
      - run: echo ${USER_ID}

  all-1b:
    name: All 1b
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJson(github) }}
    steps:
      - run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV # Sets version env var.
      - run: echo "all-1b"

  all-2:
    name: All 2
    needs: [all-1a, all-1b]
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJson(github) }}
    steps:
      - run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV # Sets version env var.
      - run: echo "all-2"

  on-master:
    # Only on master.
    if: startsWith(github.ref, 'refs/heads/master')
    needs: [all-2]
    name: On master
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJson(github) }}
    steps:
      - run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV # Sets version env var.
      - run: echo "on-master"


  on-tags:
    # Only on tags.
    if: startsWith(github.ref, 'refs/tags/')
    needs: [all-2]
    name: On tags
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJson(github) }}
    steps:
      - run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV # Sets version env var.
      - run: echo "on-tags"